# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/39e30c20-e305-4670-b82d-d836c00b1876";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-ccada6eb-393c-4ba8-a310-403b264cb35d".device = "/dev/disk/by-uuid/ccada6eb-393c-4ba8-a310-403b264cb35d";

  fileSystems."/mnt/Storage" =
    { device = "/dev/disk/by-uuid/30e90254-d8d3-4dc9-a7f9-97dda2efd116";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."Storage".device = "/dev/disk/by-uuid/31c83613-aaa1-412f-821a-01e7700c9499";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1EC2-4E5D";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.ipv6leakintrf0.useDHCP = lib.mkDefault true;
  # networking.interfaces.tun0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
